version: 0.2

# https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/sample-docker.html
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com
      - cd packages/webapi
      - wget -q https://github.com/tomodian/release/releases/download/0.13.0/release_linux_amd64.zip -O release.zip
      - unzip release.zip
      - export IMAGE_TAG=$(./release latest --any | tr -d '\n')
  build:
    commands:
      - echo Build started on `date`
      - echo Tag $IMAGE_TAG
      - echo Building the Docker image...
      - docker build -t webtools-api:$IMAGE_TAG .
      - docker tag webtools-api:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/webtools-api:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/webtools-api:$IMAGE_TAG